### ISSUE TITLE
修改 mysql toml 配置后不生效

### ISSUE THREAD

**Issue by wujunze** [bilibili/kratos#131]
1. 已经修改 MySQL 配置   
```toml
[demo]
	addr = "127.0.0.1:3306"
	dsn = "{dev}:{dev}@tcp(127.0.0.1:3306)/{mg}?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	readDSN = ["{dev}:{dev}@tcp(127.0.0.2:3306)/{mg}?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8","{dev}:{dev}@tcp(127.0.0.3:3306)/{mg}?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "200ms"
	execTimeout = "300ms"
	tranTimeout = "400ms"

```

2. 重启 kratos run 
3. 仍然报错  
```shell
[2019/05/30 15:36:00.393] [/Users/wujunze/leap/code/go/message-gateway/internal/server/http/server.go:51] ping error(Error 1045: Access denied for user '{dev}'@'172.19.0.1' (using password: YES))
[2019/05/30 15:36:00.393] [http-access-log] ip=127.0.0.1 user=no_user traceid= params= ret=0 stack=<nil> err= ts=0.031622917 path=/ping method=GET msg=0 timeout_quota=0.999984716 
```
4. 全局搜索 ip ```172.19.0.1``` 未发现这个 ip
